INSERT INTO USERS (USER_ID, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (0, 'admin', 'admin@gmail.com', 'admin', 'ADMIN');
INSERT INTO MOVIES(MOVIE_ID, TITLE, DUBBED, DIRECTOR, STORY, LENGTH, AGE_LIMIT, TICKET_SOLD) VALUES (0, 'x', false, 'x', 'x', 120, 'AGE_LIMIT_16', 0);
INSERT INTO ACTORS (ACTOR_ID, NAME, SEX, AGE, BIO) VALUES (0, 'x', 'x', 50, 'x');