INSERT INTO USERS (USER_ID, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (0, 'admin', 'admin@gmail.com', 'admin', 'ADMIN');
INSERT INTO USERS (USER_ID, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (1, 'user', 'user@gmail.com', 'user', 'USER');

INSERT INTO MOVIES(MOVIE_ID, TITLE, DUBBED, DIRECTOR, STORY, LENGTH, AGE_LIMIT, TICKET_SOLD) VALUES (0, 'PULP FICTION', true, 'TARANTINO', 'bloody stuff', 120, 'AGE_LIMIT_18', 0);
INSERT INTO MOVIES(MOVIE_ID, TITLE, DUBBED, DIRECTOR, STORY, LENGTH, AGE_LIMIT, TICKET_SOLD) VALUES (1, 'HATEFUL EIGHT', false, 'TARANTINO', 'bloody stuff', 120, 'AGE_LIMIT_18', 0);
INSERT INTO MOVIES(MOVIE_ID, TITLE, DUBBED, DIRECTOR, STORY, LENGTH, AGE_LIMIT, TICKET_SOLD) VALUES (2, 'RESERVOIR DOGS', true, 'TARANTINO', 'bloody stuff', 120, 'AGE_LIMIT_16', 0);
INSERT INTO MOVIES(MOVIE_ID, TITLE, DUBBED, DIRECTOR, STORY, LENGTH, AGE_LIMIT, TICKET_SOLD) VALUES (3, 'KILL BILL', false, 'x', 'TARANTINO', 120, 'AGE_LIMIT_18', 0);

INSERT INTO ACTORS (ACTOR_ID, NAME, SEX, AGE, BIO) VALUES (0, 'Michael', 'MALE', 32, 'X');
INSERT INTO ACTORS (ACTOR_ID, NAME, SEX, AGE, BIO) VALUES (1, 'Jane', 'FEMALE', 25, 'X');

INSERT INTO SCREENING(SCREENING_ID, START_TIME, END_TIME) VALUES (0, '2017-11-02 14:00:00', '2017-11-02 16:00:00');
INSERT INTO SCREENING(SCREENING_ID, START_TIME, END_TIME) VALUES (1, '2017-11-02 16:00:00', '2017-11-02 18:00:00');

INSERT INTO ROOMS VALUES (0, 'BARTÓK', 10, 10);
INSERT INTO ROOMS VALUES (0, 'JEDLIK', 15, 10);

INSERT INTO SCREENING_MOVIE VALUES (0, 0);
INSERT INTO SCREENING_MOVIE VALUES (0, 1);

INSERT INTO SCREENING_ROOM VALUES (0, 0);
INSERT INTO SCREENING_ROOM VALUES (1, 1);

INSERT INTO ACTOR_MOVIE VALUES (0, 1);
INSERT INTO ACTOR_MOVIE VALUES (0, 2);x